export const GET_POKEMON = "GET_POKEMON";
export const GET_DETAIL_POKEMON = "GET_DETAIL_POKEMON";
export const POST_POKEMON = "POST_POKEMON";
export const GET_TYPES = "GET_TYPES";
export const CLEAN_DETAIL = "CLEAN_DETAIL";